name: shuzzy_flutter
description: Flutter client for Shuzzy2.0 MERN backend
publish_to: 'none'
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5       # for backend API calls
  provider: ^6.0.5    # state management
  google_maps_flutter: ^2.2.2 # map integration

# assets, fonts etc.